import { notFound } from "next/navigation";

import { Badge, Card } from "@/components/ui";
import { getPublicAuction } from "@/services/auction-publishing";

export default async function AuctionDetailsPage({ params }: { params: Promise<{ auctionId: string }> }) {
  const { auctionId } = await params;
  const auction = await getPublicAuction(auctionId);
  if (!auction) notFound();
  const pricing = auction.type === "RANK" ? "Rank-based evaluation" : `${auction.bidDirection === "UPWARD" ? "Bid increment" : "Bid decrement"}: ${auction.bidStepAmount?.toString() ?? "Not specified"} ${auction.currency}`;
  return <section className="mx-auto max-w-5xl space-y-6 px-4 py-10"><Card><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm text-[var(--color-text-muted)]">{auction.auctionNumber}</p><h1 className="mt-1 text-3xl font-semibold">{auction.title}</h1></div><Badge variant="success">{auction.type}</Badge></div>{auction.description ? <p className="mt-5 text-sm leading-6 text-[var(--color-text-muted)]">{auction.description}</p> : null}</Card><Card><h2 className="text-lg font-semibold">Auction schedule</h2><dl className="mt-4 grid gap-3 text-sm md:grid-cols-2"><div><dt className="text-[var(--color-text-muted)]">Start</dt><dd>{auction.scheduledStartAt.toLocaleString()}</dd></div><div><dt className="text-[var(--color-text-muted)]">End</dt><dd>{auction.scheduledEndAt.toLocaleString()}</dd></div><div><dt className="text-[var(--color-text-muted)]">Participation</dt><dd>{auction.participationType}</dd></div><div><dt className="text-[var(--color-text-muted)]">Pricing</dt><dd>{pricing}</dd></div></dl></Card><Card><h2 className="text-lg font-semibold">Lots</h2><div className="mt-4 space-y-3">{auction.items.map((item) => <div className="border-t border-[var(--color-border)] pt-3" key={item.id}><p className="font-medium">{item.lotNumber}. {item.name}</p>{item.description ? <p className="mt-1 text-sm text-[var(--color-text-muted)]">{item.description}</p> : null}<p className="mt-1 text-sm text-[var(--color-text-muted)]">{item.quantity.toString()} {item.unit}{item.startingPrice ? ` · ${item.startingPrice.toString()} ${auction.currency}` : ""}</p></div>)}</div></Card>{auction.documents.length || auction.media.length ? <Card><h2 className="text-lg font-semibold">Public files</h2><div className="mt-4 space-y-2">{auction.documents.map((file) => <a className="block text-sm font-medium text-[var(--color-primary)] hover:underline" href={`/api/auctions/${auction.id}/files/document/${file.id}`} key={file.id}>{file.fileName ?? file.name}</a>)}{auction.media.map((file) => <a className="block text-sm font-medium text-[var(--color-primary)] hover:underline" href={`/api/auctions/${auction.id}/files/media/${file.id}`} key={file.id}>{file.fileName ?? `${file.type} file`}</a>)}</div></Card> : null}</section>;
}
