import Link from "next/link";

import { AuctionReviewActions } from "@/components/portal/auction-review-actions";
import { AuctionFileManager } from "@/components/portal/auction-file-manager";
import { Alert, Badge, Card } from "@/components/ui";
import type { getAuthorizedAuctionDraft } from "@/services/auction-drafts";

type AuctionDraft = NonNullable<Awaited<ReturnType<typeof getAuthorizedAuctionDraft>>>;

type AuditEvent = { action: string; actor: { name: string } | null; createdAt: Date };

type Files = { documents: readonly { id: string; name: string; type: string; fileName: string | null; mimeType: string | null; sizeInBytes: number | null; access: "PUBLIC" | "PRIVATE" | "INTERNAL"; auctionItemId: string | null; createdAt: Date; uploadedBy: { name: string } }[]; media: readonly { id: string; type: string; fileName: string | null; mimeType: string | null; sizeInBytes: number | null; access: "PUBLIC" | "PRIVATE" | "INTERNAL"; auctionItemId: string | null; createdAt: Date; uploadedBy: { name: string } }[]; items: readonly { id: string; lotNumber: string; name: string }[] };

export function AuctionDraftDetail({ auction, portal, rejectionReason, history = [], files }: { auction: AuctionDraft; portal: "admin" | "client"; rejectionReason?: string; history?: readonly AuditEvent[]; files?: Files }) {
  const canEdit = auction.status === "DRAFT";
  const fileEntries = files ? [...files.documents.map((file) => ({ ...file, kind: "document" as const, label: file.fileName ?? file.name })), ...files.media.map((file) => ({ ...file, kind: "media" as const, label: file.fileName ?? "Media file" }))] : [];
  return <section className="mx-auto max-w-5xl space-y-6"><Card><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm text-[var(--color-text-muted)]">{auction.auctionNumber}</p><h1 className="mt-1 text-2xl font-semibold">{auction.title}</h1><p className="mt-2 text-sm text-[var(--color-text-muted)]">{auction.clientOrganization.displayName ?? auction.clientOrganization.legalName}</p></div><Badge variant={auction.status === "DRAFT" ? "warning" : "neutral"}>{auction.status}</Badge></div>{rejectionReason ? <Alert className="mt-4" variant="danger">Rejection reason: {rejectionReason}</Alert> : null}{canEdit ? <Link className="mt-5 inline-flex text-sm font-medium text-[var(--color-primary)] hover:underline" href={`/${portal}/auctions/${auction.id}/edit`}>Edit draft</Link> : null}<AuctionReviewActions auctionId={auction.id} portal={portal} status={auction.status} /></Card><Card><h2 className="text-lg font-semibold">Auction details</h2><dl className="mt-4 grid gap-4 text-sm md:grid-cols-3"><Detail label="Type" value={auction.type} /><Detail label="Currency" value={auction.currency} /><Detail label="Visibility" value={auction.visibility} /><Detail label="Start" value={auction.scheduledStartAt.toLocaleString()} /><Detail label="End" value={auction.scheduledEndAt.toLocaleString()} /><Detail label="Timezone" value={auction.timezone} /></dl></Card><Card><h2 className="text-lg font-semibold">Items</h2><div className="mt-4 space-y-3">{auction.items.map((item) => <div className="border-t border-[var(--color-border)] pt-3" key={item.id}><p className="font-medium">{item.lotNumber}. {item.name}</p><p className="mt-1 text-sm text-[var(--color-text-muted)]">{item.quantity.toString()} {item.unit}</p></div>)}</div></Card>{files ? <AuctionFileManager auctionId={auction.id} canManage={portal === "admin" ? ["DRAFT", "SUBMITTED", "UNDER_REVIEW"].includes(auction.status) : auction.status === "DRAFT"} files={fileEntries} lots={files.items} portal={portal} /> : null}{history.length ? <Card><h2 className="text-lg font-semibold">Workflow history</h2><div className="mt-4 space-y-3">{history.map((event) => <div className="border-t border-[var(--color-border)] pt-3" key={`${event.action}-${event.createdAt.toISOString()}`}><p className="text-sm font-medium">{event.action.replaceAll("_", " ")}</p><p className="mt-1 text-xs text-[var(--color-text-muted)]">{event.actor?.name ?? "System"} · {event.createdAt.toLocaleString()}</p></div>)}</div></Card> : null}</section>;
}

function Detail({ label, value }: { label: string; value: string }) { return <div><dt className="text-[var(--color-text-muted)]">{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>; }
