import { roleHasPermission } from "../lib/permissions.ts";
import { prisma } from "../lib/prisma.ts";
import type { AuthenticatedUser } from "../types/auth.ts";

export class ParticipationReviewError extends Error {}
function reviewer(actor: AuthenticatedUser) { if ((actor.role !== "ADMIN" && actor.role !== "SUPER_ADMIN") || !roleHasPermission(actor.role, "VENDORS:APPROVE")) throw new ParticipationReviewError("You are not allowed to review participation requests."); }

export async function listParticipationRequests(actor: AuthenticatedUser) { reviewer(actor); return prisma.vendorParticipation.findMany({ where: { status: { in: ["SUBMITTED", "UNDER_REVIEW", "APPROVED", "REJECTED"] } }, orderBy: { submittedAt: "asc" }, take: 100, select: { id: true, status: true, eligibilityStatus: true, submittedAt: true, auction: { select: { id: true, auctionNumber: true, title: true, emdRequired: true } }, vendorOrganization: { select: { displayName: true, legalName: true } }, emdRecords: { select: { id: true, status: true, required: true } } } }); }

export async function approveParticipation(actor: AuthenticatedUser, participationId: string) { reviewer(actor); return prisma.$transaction(async (tx) => { const participation = await tx.vendorParticipation.findFirst({ where: { id: participationId, status: "SUBMITTED" }, include: { auction: { select: { id: true, emdRequired: true, emdAmount: true, emdCurrency: true } } } }); if (!participation) throw new ParticipationReviewError("Only submitted participation requests can be approved."); const updated = await tx.vendorParticipation.updateMany({ where: { id: participationId, status: "SUBMITTED" }, data: { status: "APPROVED", eligibilityStatus: participation.auction.emdRequired ? "PENDING" : "ELIGIBLE", approvedAt: new Date(), reviewedById: actor.id } }); if (updated.count !== 1) throw new ParticipationReviewError("This participation request has already changed state."); const emd = participation.auction.emdRequired ? await tx.emdRecord.upsert({ where: { auctionId_vendorOrganizationId: { auctionId: participation.auctionId, vendorOrganizationId: participation.vendorOrganizationId } }, create: { auctionId: participation.auctionId, vendorOrganizationId: participation.vendorOrganizationId, participationId, required: true, amount: participation.auction.emdAmount, currency: participation.auction.emdCurrency, status: "PENDING" }, update: { participationId, required: true, amount: participation.auction.emdAmount, currency: participation.auction.emdCurrency, status: "PENDING" } }) : await tx.emdRecord.upsert({ where: { auctionId_vendorOrganizationId: { auctionId: participation.auctionId, vendorOrganizationId: participation.vendorOrganizationId } }, create: { auctionId: participation.auctionId, vendorOrganizationId: participation.vendorOrganizationId, participationId, required: false, status: "NOT_REQUIRED" }, update: { participationId, required: false, status: "NOT_REQUIRED" } }); await tx.auditLog.create({ data: { actorUserId: actor.id, action: "VENDOR_PARTICIPATION_APPROVED", entityType: "VENDOR_PARTICIPATION", entityId: participationId, newValue: { auctionId: participation.auctionId, emdStatus: emd.status } } }); return { participationId, emdStatus: emd.status }; }); }

export async function rejectParticipation(actor: AuthenticatedUser, participationId: string, reason: string) { reviewer(actor); const note = reason.trim(); if (!note || note.length > 2_000) throw new ParticipationReviewError("Provide a rejection reason of 2,000 characters or fewer."); return prisma.$transaction(async (tx) => { const updated = await tx.vendorParticipation.updateMany({ where: { id: participationId, status: "SUBMITTED" }, data: { status: "REJECTED", eligibilityStatus: "INELIGIBLE", rejectedAt: new Date(), reviewedById: actor.id, reviewNote: note } }); if (updated.count !== 1) throw new ParticipationReviewError("Only submitted participation requests can be rejected."); await tx.auditLog.create({ data: { actorUserId: actor.id, action: "VENDOR_PARTICIPATION_REJECTED", entityType: "VENDOR_PARTICIPATION", entityId: participationId, newValue: { reason: note } } }); }); }

export async function verifyParticipationEmd(actor: AuthenticatedUser, participationId: string) { reviewer(actor); return prisma.$transaction(async (tx) => { const participation = await tx.vendorParticipation.findFirst({ where: { id: participationId, status: "APPROVED" }, select: { auctionId: true, vendorOrganizationId: true } }); if (!participation) throw new ParticipationReviewError("Only approved participation requests can have EMD verified."); const emd = await tx.emdRecord.updateMany({ where: { auctionId: participation.auctionId, vendorOrganizationId: participation.vendorOrganizationId, required: true, status: { in: ["PENDING", "SUBMITTED"] } }, data: { status: "VERIFIED", verifiedAt: new Date(), reviewedById: actor.id } }); if (emd.count !== 1) throw new ParticipationReviewError("A pending EMD record is required before verification."); await tx.vendorParticipation.update({ where: { id: participationId }, data: { eligibilityStatus: "ELIGIBLE" } }); await tx.auditLog.create({ data: { actorUserId: actor.id, action: "EMD_VERIFIED", entityType: "EMD_RECORD", entityId: participationId, newValue: { auctionId: participation.auctionId, participationId } } }); }); }
