import type {
  Permission,
  PermissionAction,
  PermissionArea,
  PermissionDefinition,
  Role,
  RoleDefinition,
  RolePermissionMap,
} from "../types/permissions.ts";

function createPermission(
  area: PermissionArea,
  action: PermissionAction,
): Permission {
  return `${area}:${action}`;
}

function definePermission(
  area: PermissionArea,
  action: PermissionAction,
  label: string,
  description: string,
): PermissionDefinition {
  return {
    key: createPermission(area, action),
    area,
    action,
    label,
    description,
  };
}

export const roleDefinitions = {
  SUPER_ADMIN: {
    key: "SUPER_ADMIN",
    label: "Super Admin",
    description: "Highest-level platform operator role for system ownership.",
  },
  ADMIN: {
    key: "ADMIN",
    label: "Admin",
    description: "Platform administration role for operational management.",
  },
  CLIENT: {
    key: "CLIENT",
    label: "Client",
    description: "Business client role for creating and managing auctions.",
  },
  VENDOR: {
    key: "VENDOR",
    label: "Vendor",
    description: "Supplier role for discovering auctions and participating.",
  },
  SUPPORT: {
    key: "SUPPORT",
    label: "Support",
    description: "Support role for assisting users and reviewing platform context.",
  },
} satisfies Record<Role, RoleDefinition>;

export const permissionDefinitions = [
  definePermission("PUBLIC", "VIEW", "View public pages", "Access public website routes."),

  definePermission("CLIENTS", "VIEW", "View clients", "View client account context."),
  definePermission("CLIENTS", "CREATE", "Create clients", "Create client records when supported."),
  definePermission("CLIENTS", "UPDATE", "Update clients", "Update client account context."),
  definePermission("CLIENTS", "DELETE", "Delete clients", "Delete client account context."),
  definePermission("CLIENTS", "APPROVE", "Approve clients", "Approve client onboarding."),
  definePermission("CLIENTS", "REJECT", "Reject clients", "Reject client onboarding."),
  definePermission("CLIENTS", "MANAGE", "Manage clients", "Manage client operations."),

  definePermission("VENDORS", "VIEW", "View vendors", "View vendor account context."),
  definePermission("VENDORS", "CREATE", "Create vendors", "Create vendor records when supported."),
  definePermission("VENDORS", "UPDATE", "Update vendors", "Update vendor account context."),
  definePermission("VENDORS", "DELETE", "Delete vendors", "Delete vendor account context."),
  definePermission("VENDORS", "APPROVE", "Approve vendors", "Approve vendor onboarding."),
  definePermission("VENDORS", "REJECT", "Reject vendors", "Reject vendor onboarding."),
  definePermission("VENDORS", "MANAGE", "Manage vendors", "Manage vendor operations."),

  definePermission("AUCTIONS", "VIEW", "View auctions", "View auction information."),
  definePermission("AUCTIONS", "CREATE", "Create auctions", "Create auction events when supported."),
  definePermission("AUCTIONS", "UPDATE", "Update auctions", "Update auction event details."),
  definePermission("AUCTIONS", "DELETE", "Delete auctions", "Delete auction events when supported."),
  definePermission("AUCTIONS", "APPROVE", "Approve auctions", "Approve auction publication."),
  definePermission("AUCTIONS", "REJECT", "Reject auctions", "Reject auction publication."),
  definePermission("AUCTIONS", "MANAGE", "Manage auctions", "Manage auction operations."),
  definePermission("AUCTIONS", "EXPORT", "Export auctions", "Export auction information."),
  definePermission("AUCTIONS", "PARTICIPATE", "Participate in auctions", "Join eligible auction events."),
  definePermission("AUCTIONS", "PAUSE", "Pause auctions", "Pause auction events when supported."),
  definePermission("AUCTIONS", "CANCEL", "Cancel auctions", "Cancel auction events when supported."),
  definePermission("AUCTIONS", "EXTEND", "Extend auctions", "Extend auction event timing."),

  definePermission("BIDS", "VIEW", "View bids", "View bid information."),
  definePermission("BIDS", "CREATE", "Create bids", "Create bid records when supported."),
  definePermission("BIDS", "UPDATE", "Update bids", "Update bid records when supported."),
  definePermission("BIDS", "DELETE", "Delete bids", "Delete bid records when supported."),
  definePermission("BIDS", "APPROVE", "Approve bids", "Approve bid records when supported."),
  definePermission("BIDS", "REJECT", "Reject bids", "Reject bid records when supported."),
  definePermission("BIDS", "MANAGE", "Manage bids", "Manage bid operations."),
  definePermission("BIDS", "EXPORT", "Export bids", "Export bid information."),
  definePermission("BIDS", "BID", "Submit bids", "Submit bids in eligible events."),

  definePermission("PAYMENTS", "VIEW", "View payments", "View payment-related information."),
  definePermission("PAYMENTS", "UPDATE", "Update payments", "Update payment-related information."),
  definePermission("PAYMENTS", "MANAGE", "Manage payments", "Manage payment operations when supported."),
  definePermission("PAYMENTS", "EXPORT", "Export payments", "Export payment-related information."),

  definePermission("DOCUMENTS", "VIEW", "View documents", "View platform documents."),
  definePermission("DOCUMENTS", "CREATE", "Create documents", "Create platform documents."),
  definePermission("DOCUMENTS", "UPDATE", "Update documents", "Update platform documents."),
  definePermission("DOCUMENTS", "DELETE", "Delete documents", "Delete platform documents."),
  definePermission("DOCUMENTS", "APPROVE", "Approve documents", "Approve submitted documents."),
  definePermission("DOCUMENTS", "REJECT", "Reject documents", "Reject submitted documents."),
  definePermission("DOCUMENTS", "MANAGE", "Manage documents", "Manage document operations."),
  definePermission("DOCUMENTS", "EXPORT", "Export documents", "Export document information."),

  definePermission("NOTIFICATIONS", "VIEW", "View notifications", "View platform notifications."),
  definePermission("NOTIFICATIONS", "CREATE", "Create notifications", "Create platform notifications."),
  definePermission("NOTIFICATIONS", "UPDATE", "Update notifications", "Update notification settings."),
  definePermission("NOTIFICATIONS", "DELETE", "Delete notifications", "Delete platform notifications."),
  definePermission("NOTIFICATIONS", "MANAGE", "Manage notifications", "Manage notification operations."),

  definePermission("REPORTS", "VIEW", "View reports", "View reporting information."),
  definePermission("REPORTS", "CREATE", "Create reports", "Create reports when supported."),
  definePermission("REPORTS", "EXPORT", "Export reports", "Export reporting information."),
  definePermission("REPORTS", "MANAGE", "Manage reports", "Manage reporting operations."),

  definePermission("SUPPORT", "VIEW", "View support", "View support context."),
  definePermission("SUPPORT", "CREATE", "Create support requests", "Create support requests."),
  definePermission("SUPPORT", "UPDATE", "Update support", "Update support context."),
  definePermission("SUPPORT", "MANAGE", "Manage support", "Manage support operations."),

  definePermission("SETTINGS", "VIEW", "View settings", "View settings surfaces."),
  definePermission("SETTINGS", "UPDATE", "Update settings", "Update settings surfaces."),
  definePermission("SETTINGS", "MANAGE", "Manage settings", "Manage platform settings."),
] as const satisfies readonly PermissionDefinition[];

export const permissions = permissionDefinitions.map(
  (permission) => permission.key,
) satisfies readonly Permission[];

export const rolePermissions = {
  SUPER_ADMIN: permissions,
  ADMIN: [
    "PUBLIC:VIEW",
    "CLIENTS:VIEW",
    "CLIENTS:CREATE",
    "CLIENTS:UPDATE",
    "CLIENTS:APPROVE",
    "CLIENTS:REJECT",
    "CLIENTS:MANAGE",
    "VENDORS:VIEW",
    "VENDORS:CREATE",
    "VENDORS:UPDATE",
    "VENDORS:APPROVE",
    "VENDORS:REJECT",
    "VENDORS:MANAGE",
    "AUCTIONS:VIEW",
    "AUCTIONS:CREATE",
    "AUCTIONS:UPDATE",
    "AUCTIONS:APPROVE",
    "AUCTIONS:REJECT",
    "AUCTIONS:MANAGE",
    "AUCTIONS:EXPORT",
    "AUCTIONS:PAUSE",
    "AUCTIONS:CANCEL",
    "AUCTIONS:EXTEND",
    "BIDS:VIEW",
    "BIDS:MANAGE",
    "BIDS:EXPORT",
    "PAYMENTS:VIEW",
    "PAYMENTS:UPDATE",
    "PAYMENTS:MANAGE",
    "PAYMENTS:EXPORT",
    "DOCUMENTS:VIEW",
    "DOCUMENTS:CREATE",
    "DOCUMENTS:UPDATE",
    "DOCUMENTS:DELETE",
    "DOCUMENTS:APPROVE",
    "DOCUMENTS:REJECT",
    "DOCUMENTS:MANAGE",
    "DOCUMENTS:EXPORT",
    "NOTIFICATIONS:VIEW",
    "NOTIFICATIONS:CREATE",
    "NOTIFICATIONS:UPDATE",
    "NOTIFICATIONS:DELETE",
    "NOTIFICATIONS:MANAGE",
    "REPORTS:VIEW",
    "REPORTS:CREATE",
    "REPORTS:EXPORT",
    "REPORTS:MANAGE",
    "SUPPORT:VIEW",
    "SUPPORT:UPDATE",
    "SUPPORT:MANAGE",
    "SETTINGS:VIEW",
    "SETTINGS:UPDATE",
    "SETTINGS:MANAGE",
  ],
  CLIENT: [
    "PUBLIC:VIEW",
    "AUCTIONS:VIEW",
    "AUCTIONS:CREATE",
    "AUCTIONS:UPDATE",
    "AUCTIONS:EXPORT",
    "AUCTIONS:CANCEL",
    "AUCTIONS:EXTEND",
    "BIDS:VIEW",
    "DOCUMENTS:VIEW",
    "DOCUMENTS:CREATE",
    "DOCUMENTS:UPDATE",
    "DOCUMENTS:DELETE",
    "DOCUMENTS:EXPORT",
    "NOTIFICATIONS:VIEW",
    "SUPPORT:VIEW",
    "SUPPORT:CREATE",
    "SETTINGS:VIEW",
    "SETTINGS:UPDATE",
  ],
  VENDOR: [
    "PUBLIC:VIEW",
    "AUCTIONS:VIEW",
    "AUCTIONS:PARTICIPATE",
    "BIDS:VIEW",
    "BIDS:CREATE",
    "BIDS:UPDATE",
    "BIDS:BID",
    "PAYMENTS:VIEW",
    "DOCUMENTS:VIEW",
    "DOCUMENTS:CREATE",
    "DOCUMENTS:UPDATE",
    "NOTIFICATIONS:VIEW",
    "SUPPORT:VIEW",
    "SUPPORT:CREATE",
    "SETTINGS:VIEW",
    "SETTINGS:UPDATE",
  ],
  SUPPORT: [
    "PUBLIC:VIEW",
    "CLIENTS:VIEW",
    "VENDORS:VIEW",
    "AUCTIONS:VIEW",
    "BIDS:VIEW",
    "PAYMENTS:VIEW",
    "DOCUMENTS:VIEW",
    "NOTIFICATIONS:VIEW",
    "REPORTS:VIEW",
    "SUPPORT:VIEW",
    "SUPPORT:CREATE",
    "SUPPORT:UPDATE",
    "SUPPORT:MANAGE",
    "SETTINGS:VIEW",
  ],
} as const satisfies RolePermissionMap;

export const defaultRole: Role = "VENDOR";
